# application.yaml
server:
  port: 9099
  address: 0.0.0.0
  contextPath: /

  # Tomcat specifics
  tomcat:
    uri-encoding: UTF-8
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

# Spring Configuration
#spring:
  # MySQL Connect config
  #datasource:
    #type: org.apache.commons.dbcp.BasicDataSource
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/mytest
    #username: postgres
   # password: 123456
  #application:
   # name: manage



spring:
  shardingsphere:
    name: master
    master:
      datasource:
        type: org.apache.commons.dbcp.BasicDataSource
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/mytest
        username: postgres
        password: 123456

      encrypt:
        encryptors:
          encryptor_aes:
            type: aes
            props:
              aes.key.value: 2019
        tables:
          user_info:
            columns:
              password:
                cipherColumn: password
                encryptor: encryptor_aes
              idcard:
                cipherColumn: idcard
                encryptor: encryptor_aes
        props:
          sql:
            show: true
          query:
            with:
              cipher:
                column: true


mybatis:
  mapper-locations: classpath:mapping/*.xml